import React, { useState, useRef, useEffect } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';

function RagChatbot() {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  // Function to scroll to bottom of messages
  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  // Scroll to bottom when messages change
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Handle opening/closing the chatbot
  const toggleChatbot = () => {
    setIsOpen(!isOpen);
    if (!isOpen && inputRef.current) {
      setTimeout(() => inputRef.current.focus(), 100);
    }
  };

  // Handle sending a message
  const handleSendMessage = async () => {
    if (!inputValue.trim() || isLoading) return;

    // Add user message
    const userMessage = { type: 'user', content: inputValue, timestamp: new Date() };
    setMessages(prev => [...prev, userMessage]);
    const newInputValue = inputValue;
    setInputValue('');
    setIsLoading(true);

    try {
      // Simulate API call to RAG backend
      // In a real implementation, this would call your FastAPI backend
      await new Promise(resolve => setTimeout(resolve, 1000)); // Simulate network delay

      // Get current page context
      const currentPageTitle = typeof window !== 'undefined' ? document.title : '';
      const selectedText = typeof window !== 'undefined'
        ? window.getSelection()?.toString() || ''
        : '';

      // Generate bot response based on context
      let botResponse = '';

      if (selectedText) {
        // If text is selected, respond based on selected text
        botResponse = `Based on the selected text "${selectedText.substring(0, 50)}...", I can provide more information. This is a simulated response - in a real implementation, this would be generated by the RAG system using the selected text as context.`;
      } else {
        // Otherwise, respond based on current page
        botResponse = `Regarding "${currentPageTitle}", I can help explain concepts related to Physical AI and Humanoid Robotics. This is a simulated response - in a real implementation, this would be generated by the RAG system using the current page content as context.`;
      }

      // Add bot response
      const botMessage = {
        type: 'bot',
        content: botResponse,
        timestamp: new Date(),
        source: selectedText ? 'selected-text' : 'full-book'
      };
      setMessages(prev => [...prev, botMessage]);
    } catch (error) {
      const errorMessage = {
        type: 'bot',
        content: 'Sorry, I encountered an error processing your request. Please try again.',
        timestamp: new Date()
      };
      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  // Handle key press (Enter to send)
  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  // Close chatbot when clicking outside
  useEffect(() => {
    const handleClickOutside = (event) => {
      const chatbotElement = document.querySelector('.chatbot-drawer');
      const chatbotButton = document.querySelector('.chatbot-button');

      if (isOpen &&
          chatbotElement &&
          !chatbotElement.contains(event.target) &&
          chatbotButton &&
          !chatbotButton.contains(event.target)) {
        setIsOpen(false);
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  // Listen for custom event to open chatbot
  useEffect(() => {
    const handleOpenEvent = () => {
      setIsOpen(true);
    };

    window.addEventListener('openRagChatbot', handleOpenEvent);
    return () => {
      window.removeEventListener('openRagChatbot', handleOpenEvent);
    };
  }, []);

  return (
    <BrowserOnly>
      {() => (
        <div className="floating-chatbot">
          <button className="chatbot-button" onClick={toggleChatbot}>
            🤖
          </button>

          {isOpen && (
            <div className="chatbot-drawer open">
              <div className="chatbot-header">
                <span>Physical AI Assistant</span>
                <button className="chatbot-close" onClick={() => setIsOpen(false)}>
                  ×
                </button>
              </div>

              <div className="chatbot-messages">
                {messages.length === 0 ? (
                  <div className="chatbot-message bot">
                    Hello! I'm your Physical AI & Humanoid Robotics assistant.
                    Ask me anything about the current content or select text to get specific explanations.
                    <br /><br />
                    <strong>Modes:</strong>
                    <ul>
                      <li><strong>Full Book Mode:</strong> Answers from entire textbook</li>
                      <li><strong>Selected Text Mode:</strong> Answers only from highlighted text</li>
                    </ul>
                  </div>
                ) : (
                  messages.map((message, index) => (
                    <div
                      key={index}
                      className={`chatbot-message ${message.type}`}
                    >
                      {message.content}
                      {message.source === 'selected-text' && (
                        <small style={{display: 'block', marginTop: '0.25rem', opacity: 0.7}}>
                          Answer based on selected text
                        </small>
                      )}
                    </div>
                  ))
                )}
                {isLoading && (
                  <div className="chatbot-message bot">
                    Thinking...
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              <div className="chatbot-input-area">
                <textarea
                  ref={inputRef}
                  className="chatbot-input"
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyPress={handleKeyPress}
                  placeholder="Ask about Physical AI concepts..."
                  rows="2"
                />
                <button
                  className="chatbot-send"
                  onClick={handleSendMessage}
                  disabled={isLoading || !inputValue.trim()}
                >
                  {isLoading ? '...' : 'Send'}
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </BrowserOnly>
  );
}

export default RagChatbot;